# Generated by Django 3.2.10 on 2022-01-06 04:13

from django.db import migrations
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0003_alter_event_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='data',
            field=jsonfield.fields.JSONField(blank=True, default=''),
        ),
    ]
